version: 0.0
os: linux
files:
  - source: s3://codepipeline-us-east-1-600425472893/Deployment-Testing/SourceArti/
    destination: /var/www/html/
hooks:
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
